---
title: "Data Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(tidyverse)

library(p8105.datasets)

library(flexdashboard)
library(plotly)
```

```{r importing_and_tidying, echo = FALSE, message = FALSE, warning = FALSE}
data("rest_inspec") # importing data

rest_inspec = rest_inspec %>% 
  drop_na(boro, critical_flag, inspection_date, score) %>% 
  filter(
    boro != "Missing", # was originally found to have both NA and "Missing" values
    score > 0 # was originally found to have negative scores, which does not sound reasonable to have
  ) %>% 
  mutate(
    inspection_date_2 = as.Date(inspection_date),
    year = year(inspection_date),
    month = month(inspection_date),
    day = day(inspection_date)
  ) %>% 
  slice_sample(n = 5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r score_vs_boro, echo = FALSE, warning = FALSE}
rest_inspec %>% 
  plot_ly(
  x = ~boro, y = ~score, type = "box", mode = "markers", color = ~boro)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r score_vs_inspection_date, echo = FALSE, warning = FALSE}
rest_inspec %>% 
  plot_ly(
    x = ~year, y = ~score, type = "scatter", mode = "markers", color = ~boro)
```

### Chart C

```{r score_critical_flag, echo = FALSE, warning = FALSE}
rest_inspec %>% 
  plot_ly(
    x = ~grade, y = ~score, type = "bar", mode = "markers", color = ~boro)
```